language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="containers:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="containers" OCAML_VERSION="4.02.3" EXTRA_DEPS="base-threads base-unix" TESTS=false
  - PACKAGE="containers" OCAML_VERSION="4.03" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.04" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.05" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.06" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.07" EXTRA_DEPS="base-threads base-unix"
  - PACKAGE="containers" OCAML_VERSION="4.08" EXTRA_DEPS="base-threads base-unix" TESTS=false
